create table accounts (id bigint not null auto_increment, description varchar(255), number varchar(255), primary key (id))
create table customers (id bigint not null auto_increment, name varchar(255), primary key (id))
create table customers_phones (customers_id bigint not null, phone_numbers_id bigint not null, primary key (customers_id, phone_numbers_id))
create table items (id bigint not null auto_increment, quantity integer not null, order_id bigint, product_id bigint, primary key (id))
create table orders (id bigint not null auto_increment, created_at datetime, customer_id bigint, primary key (id))
create table person (id bigint not null auto_increment, first_name varchar(255), last_name varchar(255), primary key (id))
create table phone_numbers (id bigint not null auto_increment, value varchar(255), primary key (id))
create table products (id bigint not null auto_increment, name varchar(255), primary key (id))
alter table customers_phones add constraint FKmsf59h0dvh6595tnngfkdoxi2 foreign key (phone_numbers_id) references phone_numbers (id)
alter table customers_phones add constraint FKakgk8pmdmgmum180k673xw87l foreign key (customers_id) references customers (id)
alter table items add constraint FKirjef006njdi706iiqdfkgk9d foreign key (order_id) references orders (id)
alter table items add constraint FKmtk37pxnx7d5ck7fkq2xcna4i foreign key (product_id) references products (id)
alter table orders add constraint FKpxtb8awmi0dk6smoh2vp1litg foreign key (customer_id) references customers (id)
